/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreinoRouteImport } from './routes/_authenticated/treino'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedExamBoardsRouteImport } from './routes/_authenticated/exam-boards'
import { Route as AuthenticatedExamBasesRouteImport } from './routes/_authenticated/exam-bases'
import { Route as AuthenticatedEvolucaoComoFuncionaRouteImport } from './routes/_authenticated/evolucao-como-funciona'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout-success'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedTreinoIndexRouteImport } from './routes/_authenticated/treino/index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedTreinoRetentativaRouteImport } from './routes/_authenticated/treino/retentativa'
import { Route as AuthenticatedTreinoProvaRouteImport } from './routes/_authenticated/treino/prova'
import { Route as AuthenticatedTreinoNovoRouteImport } from './routes/_authenticated/treino/novo'
import { Route as AuthenticatedTreinoFinalRouteImport } from './routes/_authenticated/treino/final'
import { Route as AuthenticatedTreinoEstudoRouteImport } from './routes/_authenticated/treino/estudo'
import { Route as AuthenticatedTreinoDiagnosticoRouteImport } from './routes/_authenticated/treino/diagnostico'
import { Route as AuthenticatedTreinoTrainingIdRouteImport } from './routes/_authenticated/treino/$trainingId'
import { Route as AuthenticatedTreinoTrainingIdIndexRouteImport } from './routes/_authenticated/treino/$trainingId/index'
import { Route as AuthenticatedExamsExamBoardIndexRouteImport } from './routes/_authenticated/exams/$examBoard/index'
import { Route as AuthenticatedTreinoTrainingIdRetentativaRouteImport } from './routes/_authenticated/treino/$trainingId/retentativa'
import { Route as AuthenticatedTreinoTrainingIdProvaRouteImport } from './routes/_authenticated/treino/$trainingId/prova'
import { Route as AuthenticatedTreinoTrainingIdFinalRouteImport } from './routes/_authenticated/treino/$trainingId/final'
import { Route as AuthenticatedTreinoTrainingIdEstudoRouteImport } from './routes/_authenticated/treino/$trainingId/estudo'
import { Route as AuthenticatedTreinoTrainingIdDiagnosticoRouteImport } from './routes/_authenticated/treino/$trainingId/diagnostico'
import { Route as AuthenticatedExamsExamBoardExamIdRouteImport } from './routes/_authenticated/exams/$examBoard/$examId'
import { Route as AuthenticatedTreinoTrainingIdRetentativaIndexRouteImport } from './routes/_authenticated/treino/$trainingId/retentativa/index'
import { Route as AuthenticatedTreinoTrainingIdEstudoIndexRouteImport } from './routes/_authenticated/treino/$trainingId/estudo/index'
import { Route as AuthenticatedExamsExamBoardExamIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/index'
import { Route as AuthenticatedTreinoTrainingIdRetentativaProvaRouteImport } from './routes/_authenticated/treino/$trainingId/retentativa/prova'
import { Route as AuthenticatedTreinoTrainingIdEstudoStudyItemIdRouteImport } from './routes/_authenticated/treino/$trainingId/estudo/$studyItemId'
import { Route as AuthenticatedExamsExamBoardExamIdQuestoesRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/questoes'
import { Route as AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/$attemptId/index'
import { Route as AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreinoRoute = AuthenticatedTreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamBoardsRoute = AuthenticatedExamBoardsRouteImport.update({
  id: '/exam-boards',
  path: '/exam-boards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamBasesRoute = AuthenticatedExamBasesRouteImport.update({
  id: '/exam-bases',
  path: '/exam-bases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvolucaoComoFuncionaRoute =
  AuthenticatedEvolucaoComoFuncionaRouteImport.update({
    id: '/evolucao-como-funciona',
    path: '/evolucao-como-funciona',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout-success',
    path: '/checkout-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTreinoIndexRoute =
  AuthenticatedTreinoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const AuthenticatedTreinoRetentativaRoute =
  AuthenticatedTreinoRetentativaRouteImport.update({
    id: '/retentativa',
    path: '/retentativa',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoProvaRoute =
  AuthenticatedTreinoProvaRouteImport.update({
    id: '/prova',
    path: '/prova',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoNovoRoute = AuthenticatedTreinoNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AuthenticatedTreinoRoute,
} as any)
const AuthenticatedTreinoFinalRoute =
  AuthenticatedTreinoFinalRouteImport.update({
    id: '/final',
    path: '/final',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoEstudoRoute =
  AuthenticatedTreinoEstudoRouteImport.update({
    id: '/estudo',
    path: '/estudo',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoDiagnosticoRoute =
  AuthenticatedTreinoDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoTrainingIdRoute =
  AuthenticatedTreinoTrainingIdRouteImport.update({
    id: '/$trainingId',
    path: '/$trainingId',
    getParentRoute: () => AuthenticatedTreinoRoute,
  } as any)
const AuthenticatedTreinoTrainingIdIndexRoute =
  AuthenticatedTreinoTrainingIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedExamsExamBoardIndexRoute =
  AuthenticatedExamsExamBoardIndexRouteImport.update({
    id: '/$examBoard/',
    path: '/$examBoard/',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedTreinoTrainingIdRetentativaRoute =
  AuthenticatedTreinoTrainingIdRetentativaRouteImport.update({
    id: '/retentativa',
    path: '/retentativa',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedTreinoTrainingIdProvaRoute =
  AuthenticatedTreinoTrainingIdProvaRouteImport.update({
    id: '/prova',
    path: '/prova',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedTreinoTrainingIdFinalRoute =
  AuthenticatedTreinoTrainingIdFinalRouteImport.update({
    id: '/final',
    path: '/final',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedTreinoTrainingIdEstudoRoute =
  AuthenticatedTreinoTrainingIdEstudoRouteImport.update({
    id: '/estudo',
    path: '/estudo',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedTreinoTrainingIdDiagnosticoRoute =
  AuthenticatedTreinoTrainingIdDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdRoute =
  AuthenticatedExamsExamBoardExamIdRouteImport.update({
    id: '/$examBoard/$examId',
    path: '/$examBoard/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedTreinoTrainingIdRetentativaIndexRoute =
  AuthenticatedTreinoTrainingIdRetentativaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRetentativaRoute,
  } as any)
const AuthenticatedTreinoTrainingIdEstudoIndexRoute =
  AuthenticatedTreinoTrainingIdEstudoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTreinoTrainingIdEstudoRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedTreinoTrainingIdRetentativaProvaRoute =
  AuthenticatedTreinoTrainingIdRetentativaProvaRouteImport.update({
    id: '/prova',
    path: '/prova',
    getParentRoute: () => AuthenticatedTreinoTrainingIdRetentativaRoute,
  } as any)
const AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute =
  AuthenticatedTreinoTrainingIdEstudoStudyItemIdRouteImport.update({
    id: '/$studyItemId',
    path: '/$studyItemId',
    getParentRoute: () => AuthenticatedTreinoTrainingIdEstudoRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdQuestoesRoute =
  AuthenticatedExamsExamBoardExamIdQuestoesRouteImport.update({
    id: '/questoes',
    path: '/questoes',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport.update({
    id: '/$attemptId/',
    path: '/$attemptId/',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute =
  AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport.update({
    id: '/$attemptId/feedback',
    path: '/$attemptId/feedback',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/exam-bases': typeof AuthenticatedExamBasesRoute
  '/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/treino': typeof AuthenticatedTreinoRouteWithChildren
  '/treino/$trainingId': typeof AuthenticatedTreinoTrainingIdRouteWithChildren
  '/treino/diagnostico': typeof AuthenticatedTreinoDiagnosticoRoute
  '/treino/estudo': typeof AuthenticatedTreinoEstudoRoute
  '/treino/final': typeof AuthenticatedTreinoFinalRoute
  '/treino/novo': typeof AuthenticatedTreinoNovoRoute
  '/treino/prova': typeof AuthenticatedTreinoProvaRoute
  '/treino/retentativa': typeof AuthenticatedTreinoRetentativaRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/treino/': typeof AuthenticatedTreinoIndexRoute
  '/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
  '/treino/$trainingId/diagnostico': typeof AuthenticatedTreinoTrainingIdDiagnosticoRoute
  '/treino/$trainingId/estudo': typeof AuthenticatedTreinoTrainingIdEstudoRouteWithChildren
  '/treino/$trainingId/final': typeof AuthenticatedTreinoTrainingIdFinalRoute
  '/treino/$trainingId/prova': typeof AuthenticatedTreinoTrainingIdProvaRoute
  '/treino/$trainingId/retentativa': typeof AuthenticatedTreinoTrainingIdRetentativaRouteWithChildren
  '/exams/$examBoard/': typeof AuthenticatedExamsExamBoardIndexRoute
  '/treino/$trainingId/': typeof AuthenticatedTreinoTrainingIdIndexRoute
  '/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/treino/$trainingId/estudo/$studyItemId': typeof AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute
  '/treino/$trainingId/retentativa/prova': typeof AuthenticatedTreinoTrainingIdRetentativaProvaRoute
  '/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/treino/$trainingId/estudo/': typeof AuthenticatedTreinoTrainingIdEstudoIndexRoute
  '/treino/$trainingId/retentativa/': typeof AuthenticatedTreinoTrainingIdRetentativaIndexRoute
  '/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/exam-bases': typeof AuthenticatedExamBasesRoute
  '/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/treino/diagnostico': typeof AuthenticatedTreinoDiagnosticoRoute
  '/treino/estudo': typeof AuthenticatedTreinoEstudoRoute
  '/treino/final': typeof AuthenticatedTreinoFinalRoute
  '/treino/novo': typeof AuthenticatedTreinoNovoRoute
  '/treino/prova': typeof AuthenticatedTreinoProvaRoute
  '/treino/retentativa': typeof AuthenticatedTreinoRetentativaRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/treino': typeof AuthenticatedTreinoIndexRoute
  '/treino/$trainingId/diagnostico': typeof AuthenticatedTreinoTrainingIdDiagnosticoRoute
  '/treino/$trainingId/final': typeof AuthenticatedTreinoTrainingIdFinalRoute
  '/treino/$trainingId/prova': typeof AuthenticatedTreinoTrainingIdProvaRoute
  '/exams/$examBoard': typeof AuthenticatedExamsExamBoardIndexRoute
  '/treino/$trainingId': typeof AuthenticatedTreinoTrainingIdIndexRoute
  '/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/treino/$trainingId/estudo/$studyItemId': typeof AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute
  '/treino/$trainingId/retentativa/prova': typeof AuthenticatedTreinoTrainingIdRetentativaProvaRoute
  '/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/treino/$trainingId/estudo': typeof AuthenticatedTreinoTrainingIdEstudoIndexRoute
  '/treino/$trainingId/retentativa': typeof AuthenticatedTreinoTrainingIdRetentativaIndexRoute
  '/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/exams/$examBoard/$examId/$attemptId': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/_authenticated/exam-bases': typeof AuthenticatedExamBasesRoute
  '/_authenticated/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/treino': typeof AuthenticatedTreinoRouteWithChildren
  '/_authenticated/treino/$trainingId': typeof AuthenticatedTreinoTrainingIdRouteWithChildren
  '/_authenticated/treino/diagnostico': typeof AuthenticatedTreinoDiagnosticoRoute
  '/_authenticated/treino/estudo': typeof AuthenticatedTreinoEstudoRoute
  '/_authenticated/treino/final': typeof AuthenticatedTreinoFinalRoute
  '/_authenticated/treino/novo': typeof AuthenticatedTreinoNovoRoute
  '/_authenticated/treino/prova': typeof AuthenticatedTreinoProvaRoute
  '/_authenticated/treino/retentativa': typeof AuthenticatedTreinoRetentativaRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/treino/': typeof AuthenticatedTreinoIndexRoute
  '/_authenticated/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
  '/_authenticated/treino/$trainingId/diagnostico': typeof AuthenticatedTreinoTrainingIdDiagnosticoRoute
  '/_authenticated/treino/$trainingId/estudo': typeof AuthenticatedTreinoTrainingIdEstudoRouteWithChildren
  '/_authenticated/treino/$trainingId/final': typeof AuthenticatedTreinoTrainingIdFinalRoute
  '/_authenticated/treino/$trainingId/prova': typeof AuthenticatedTreinoTrainingIdProvaRoute
  '/_authenticated/treino/$trainingId/retentativa': typeof AuthenticatedTreinoTrainingIdRetentativaRouteWithChildren
  '/_authenticated/exams/$examBoard/': typeof AuthenticatedExamsExamBoardIndexRoute
  '/_authenticated/treino/$trainingId/': typeof AuthenticatedTreinoTrainingIdIndexRoute
  '/_authenticated/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/_authenticated/treino/$trainingId/estudo/$studyItemId': typeof AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute
  '/_authenticated/treino/$trainingId/retentativa/prova': typeof AuthenticatedTreinoTrainingIdRetentativaProvaRoute
  '/_authenticated/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/_authenticated/treino/$trainingId/estudo/': typeof AuthenticatedTreinoTrainingIdEstudoIndexRoute
  '/_authenticated/treino/$trainingId/retentativa/': typeof AuthenticatedTreinoTrainingIdRetentativaIndexRoute
  '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/_authenticated/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/checkout-success'
    | '/dashboard'
    | '/database'
    | '/evolucao-como-funciona'
    | '/exam-bases'
    | '/exam-boards'
    | '/exams'
    | '/history'
    | '/onboarding'
    | '/planos'
    | '/treino'
    | '/treino/$trainingId'
    | '/treino/diagnostico'
    | '/treino/estudo'
    | '/treino/final'
    | '/treino/novo'
    | '/treino/prova'
    | '/treino/retentativa'
    | '/exams/'
    | '/treino/'
    | '/exams/$examBoard/$examId'
    | '/treino/$trainingId/diagnostico'
    | '/treino/$trainingId/estudo'
    | '/treino/$trainingId/final'
    | '/treino/$trainingId/prova'
    | '/treino/$trainingId/retentativa'
    | '/exams/$examBoard/'
    | '/treino/$trainingId/'
    | '/exams/$examBoard/$examId/questoes'
    | '/treino/$trainingId/estudo/$studyItemId'
    | '/treino/$trainingId/retentativa/prova'
    | '/exams/$examBoard/$examId/'
    | '/treino/$trainingId/estudo/'
    | '/treino/$trainingId/retentativa/'
    | '/exams/$examBoard/$examId/$attemptId/feedback'
    | '/exams/$examBoard/$examId/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/checkout-success'
    | '/dashboard'
    | '/database'
    | '/evolucao-como-funciona'
    | '/exam-bases'
    | '/exam-boards'
    | '/history'
    | '/onboarding'
    | '/planos'
    | '/treino/diagnostico'
    | '/treino/estudo'
    | '/treino/final'
    | '/treino/novo'
    | '/treino/prova'
    | '/treino/retentativa'
    | '/exams'
    | '/treino'
    | '/treino/$trainingId/diagnostico'
    | '/treino/$trainingId/final'
    | '/treino/$trainingId/prova'
    | '/exams/$examBoard'
    | '/treino/$trainingId'
    | '/exams/$examBoard/$examId/questoes'
    | '/treino/$trainingId/estudo/$studyItemId'
    | '/treino/$trainingId/retentativa/prova'
    | '/exams/$examBoard/$examId'
    | '/treino/$trainingId/estudo'
    | '/treino/$trainingId/retentativa'
    | '/exams/$examBoard/$examId/$attemptId/feedback'
    | '/exams/$examBoard/$examId/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/account'
    | '/_authenticated/checkout-success'
    | '/_authenticated/dashboard'
    | '/_authenticated/database'
    | '/_authenticated/evolucao-como-funciona'
    | '/_authenticated/exam-bases'
    | '/_authenticated/exam-boards'
    | '/_authenticated/exams'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/planos'
    | '/_authenticated/treino'
    | '/_authenticated/treino/$trainingId'
    | '/_authenticated/treino/diagnostico'
    | '/_authenticated/treino/estudo'
    | '/_authenticated/treino/final'
    | '/_authenticated/treino/novo'
    | '/_authenticated/treino/prova'
    | '/_authenticated/treino/retentativa'
    | '/_authenticated/exams/'
    | '/_authenticated/treino/'
    | '/_authenticated/exams/$examBoard/$examId'
    | '/_authenticated/treino/$trainingId/diagnostico'
    | '/_authenticated/treino/$trainingId/estudo'
    | '/_authenticated/treino/$trainingId/final'
    | '/_authenticated/treino/$trainingId/prova'
    | '/_authenticated/treino/$trainingId/retentativa'
    | '/_authenticated/exams/$examBoard/'
    | '/_authenticated/treino/$trainingId/'
    | '/_authenticated/exams/$examBoard/$examId/questoes'
    | '/_authenticated/treino/$trainingId/estudo/$studyItemId'
    | '/_authenticated/treino/$trainingId/retentativa/prova'
    | '/_authenticated/exams/$examBoard/$examId/'
    | '/_authenticated/treino/$trainingId/estudo/'
    | '/_authenticated/treino/$trainingId/retentativa/'
    | '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'
    | '/_authenticated/exams/$examBoard/$examId/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/treino': {
      id: '/_authenticated/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof AuthenticatedTreinoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-boards': {
      id: '/_authenticated/exam-boards'
      path: '/exam-boards'
      fullPath: '/exam-boards'
      preLoaderRoute: typeof AuthenticatedExamBoardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-bases': {
      id: '/_authenticated/exam-bases'
      path: '/exam-bases'
      fullPath: '/exam-bases'
      preLoaderRoute: typeof AuthenticatedExamBasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evolucao-como-funciona': {
      id: '/_authenticated/evolucao-como-funciona'
      path: '/evolucao-como-funciona'
      fullPath: '/evolucao-como-funciona'
      preLoaderRoute: typeof AuthenticatedEvolucaoComoFuncionaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout-success': {
      id: '/_authenticated/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treino/': {
      id: '/_authenticated/treino/'
      path: '/'
      fullPath: '/treino/'
      preLoaderRoute: typeof AuthenticatedTreinoIndexRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/treino/retentativa': {
      id: '/_authenticated/treino/retentativa'
      path: '/retentativa'
      fullPath: '/treino/retentativa'
      preLoaderRoute: typeof AuthenticatedTreinoRetentativaRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/prova': {
      id: '/_authenticated/treino/prova'
      path: '/prova'
      fullPath: '/treino/prova'
      preLoaderRoute: typeof AuthenticatedTreinoProvaRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/novo': {
      id: '/_authenticated/treino/novo'
      path: '/novo'
      fullPath: '/treino/novo'
      preLoaderRoute: typeof AuthenticatedTreinoNovoRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/final': {
      id: '/_authenticated/treino/final'
      path: '/final'
      fullPath: '/treino/final'
      preLoaderRoute: typeof AuthenticatedTreinoFinalRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/estudo': {
      id: '/_authenticated/treino/estudo'
      path: '/estudo'
      fullPath: '/treino/estudo'
      preLoaderRoute: typeof AuthenticatedTreinoEstudoRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/diagnostico': {
      id: '/_authenticated/treino/diagnostico'
      path: '/diagnostico'
      fullPath: '/treino/diagnostico'
      preLoaderRoute: typeof AuthenticatedTreinoDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/$trainingId': {
      id: '/_authenticated/treino/$trainingId'
      path: '/$trainingId'
      fullPath: '/treino/$trainingId'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdRouteImport
      parentRoute: typeof AuthenticatedTreinoRoute
    }
    '/_authenticated/treino/$trainingId/': {
      id: '/_authenticated/treino/$trainingId/'
      path: '/'
      fullPath: '/treino/$trainingId/'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdIndexRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/exams/$examBoard/': {
      id: '/_authenticated/exams/$examBoard/'
      path: '/$examBoard'
      fullPath: '/exams/$examBoard/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/treino/$trainingId/retentativa': {
      id: '/_authenticated/treino/$trainingId/retentativa'
      path: '/retentativa'
      fullPath: '/treino/$trainingId/retentativa'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdRetentativaRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/treino/$trainingId/prova': {
      id: '/_authenticated/treino/$trainingId/prova'
      path: '/prova'
      fullPath: '/treino/$trainingId/prova'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdProvaRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/treino/$trainingId/final': {
      id: '/_authenticated/treino/$trainingId/final'
      path: '/final'
      fullPath: '/treino/$trainingId/final'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdFinalRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/treino/$trainingId/estudo': {
      id: '/_authenticated/treino/$trainingId/estudo'
      path: '/estudo'
      fullPath: '/treino/$trainingId/estudo'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdEstudoRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/treino/$trainingId/diagnostico': {
      id: '/_authenticated/treino/$trainingId/diagnostico'
      path: '/diagnostico'
      fullPath: '/treino/$trainingId/diagnostico'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId': {
      id: '/_authenticated/exams/$examBoard/$examId'
      path: '/$examBoard/$examId'
      fullPath: '/exams/$examBoard/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/treino/$trainingId/retentativa/': {
      id: '/_authenticated/treino/$trainingId/retentativa/'
      path: '/'
      fullPath: '/treino/$trainingId/retentativa/'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdRetentativaIndexRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRetentativaRoute
    }
    '/_authenticated/treino/$trainingId/estudo/': {
      id: '/_authenticated/treino/$trainingId/estudo/'
      path: '/'
      fullPath: '/treino/$trainingId/estudo/'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdEstudoIndexRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdEstudoRoute
    }
    '/_authenticated/exams/$examBoard/$examId/': {
      id: '/_authenticated/exams/$examBoard/$examId/'
      path: '/'
      fullPath: '/exams/$examBoard/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/treino/$trainingId/retentativa/prova': {
      id: '/_authenticated/treino/$trainingId/retentativa/prova'
      path: '/prova'
      fullPath: '/treino/$trainingId/retentativa/prova'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdRetentativaProvaRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdRetentativaRoute
    }
    '/_authenticated/treino/$trainingId/estudo/$studyItemId': {
      id: '/_authenticated/treino/$trainingId/estudo/$studyItemId'
      path: '/$studyItemId'
      fullPath: '/treino/$trainingId/estudo/$studyItemId'
      preLoaderRoute: typeof AuthenticatedTreinoTrainingIdEstudoStudyItemIdRouteImport
      parentRoute: typeof AuthenticatedTreinoTrainingIdEstudoRoute
    }
    '/_authenticated/exams/$examBoard/$examId/questoes': {
      id: '/_authenticated/exams/$examBoard/$examId/questoes'
      path: '/questoes'
      fullPath: '/exams/$examBoard/$examId/questoes'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdQuestoesRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/$attemptId/': {
      id: '/_authenticated/exams/$examBoard/$examId/$attemptId/'
      path: '/$attemptId'
      fullPath: '/exams/$examBoard/$examId/$attemptId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback': {
      id: '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'
      path: '/$attemptId/feedback'
      fullPath: '/exams/$examBoard/$examId/$attemptId/feedback'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
  }
}

interface AuthenticatedExamsExamBoardExamIdRouteChildren {
  AuthenticatedExamsExamBoardExamIdQuestoesRoute: typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  AuthenticatedExamsExamBoardExamIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}

const AuthenticatedExamsExamBoardExamIdRouteChildren: AuthenticatedExamsExamBoardExamIdRouteChildren =
  {
    AuthenticatedExamsExamBoardExamIdQuestoesRoute:
      AuthenticatedExamsExamBoardExamIdQuestoesRoute,
    AuthenticatedExamsExamBoardExamIdIndexRoute:
      AuthenticatedExamsExamBoardExamIdIndexRoute,
    AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute:
      AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute,
    AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute:
      AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute,
  }

const AuthenticatedExamsExamBoardExamIdRouteWithChildren =
  AuthenticatedExamsExamBoardExamIdRoute._addFileChildren(
    AuthenticatedExamsExamBoardExamIdRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedExamsExamBoardExamIdRoute: typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
  AuthenticatedExamsExamBoardIndexRoute: typeof AuthenticatedExamsExamBoardIndexRoute
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedExamsExamBoardExamIdRoute:
    AuthenticatedExamsExamBoardExamIdRouteWithChildren,
  AuthenticatedExamsExamBoardIndexRoute: AuthenticatedExamsExamBoardIndexRoute,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedTreinoTrainingIdEstudoRouteChildren {
  AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute: typeof AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute
  AuthenticatedTreinoTrainingIdEstudoIndexRoute: typeof AuthenticatedTreinoTrainingIdEstudoIndexRoute
}

const AuthenticatedTreinoTrainingIdEstudoRouteChildren: AuthenticatedTreinoTrainingIdEstudoRouteChildren =
  {
    AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute:
      AuthenticatedTreinoTrainingIdEstudoStudyItemIdRoute,
    AuthenticatedTreinoTrainingIdEstudoIndexRoute:
      AuthenticatedTreinoTrainingIdEstudoIndexRoute,
  }

const AuthenticatedTreinoTrainingIdEstudoRouteWithChildren =
  AuthenticatedTreinoTrainingIdEstudoRoute._addFileChildren(
    AuthenticatedTreinoTrainingIdEstudoRouteChildren,
  )

interface AuthenticatedTreinoTrainingIdRetentativaRouteChildren {
  AuthenticatedTreinoTrainingIdRetentativaProvaRoute: typeof AuthenticatedTreinoTrainingIdRetentativaProvaRoute
  AuthenticatedTreinoTrainingIdRetentativaIndexRoute: typeof AuthenticatedTreinoTrainingIdRetentativaIndexRoute
}

const AuthenticatedTreinoTrainingIdRetentativaRouteChildren: AuthenticatedTreinoTrainingIdRetentativaRouteChildren =
  {
    AuthenticatedTreinoTrainingIdRetentativaProvaRoute:
      AuthenticatedTreinoTrainingIdRetentativaProvaRoute,
    AuthenticatedTreinoTrainingIdRetentativaIndexRoute:
      AuthenticatedTreinoTrainingIdRetentativaIndexRoute,
  }

const AuthenticatedTreinoTrainingIdRetentativaRouteWithChildren =
  AuthenticatedTreinoTrainingIdRetentativaRoute._addFileChildren(
    AuthenticatedTreinoTrainingIdRetentativaRouteChildren,
  )

interface AuthenticatedTreinoTrainingIdRouteChildren {
  AuthenticatedTreinoTrainingIdDiagnosticoRoute: typeof AuthenticatedTreinoTrainingIdDiagnosticoRoute
  AuthenticatedTreinoTrainingIdEstudoRoute: typeof AuthenticatedTreinoTrainingIdEstudoRouteWithChildren
  AuthenticatedTreinoTrainingIdFinalRoute: typeof AuthenticatedTreinoTrainingIdFinalRoute
  AuthenticatedTreinoTrainingIdProvaRoute: typeof AuthenticatedTreinoTrainingIdProvaRoute
  AuthenticatedTreinoTrainingIdRetentativaRoute: typeof AuthenticatedTreinoTrainingIdRetentativaRouteWithChildren
  AuthenticatedTreinoTrainingIdIndexRoute: typeof AuthenticatedTreinoTrainingIdIndexRoute
}

const AuthenticatedTreinoTrainingIdRouteChildren: AuthenticatedTreinoTrainingIdRouteChildren =
  {
    AuthenticatedTreinoTrainingIdDiagnosticoRoute:
      AuthenticatedTreinoTrainingIdDiagnosticoRoute,
    AuthenticatedTreinoTrainingIdEstudoRoute:
      AuthenticatedTreinoTrainingIdEstudoRouteWithChildren,
    AuthenticatedTreinoTrainingIdFinalRoute:
      AuthenticatedTreinoTrainingIdFinalRoute,
    AuthenticatedTreinoTrainingIdProvaRoute:
      AuthenticatedTreinoTrainingIdProvaRoute,
    AuthenticatedTreinoTrainingIdRetentativaRoute:
      AuthenticatedTreinoTrainingIdRetentativaRouteWithChildren,
    AuthenticatedTreinoTrainingIdIndexRoute:
      AuthenticatedTreinoTrainingIdIndexRoute,
  }

const AuthenticatedTreinoTrainingIdRouteWithChildren =
  AuthenticatedTreinoTrainingIdRoute._addFileChildren(
    AuthenticatedTreinoTrainingIdRouteChildren,
  )

interface AuthenticatedTreinoRouteChildren {
  AuthenticatedTreinoTrainingIdRoute: typeof AuthenticatedTreinoTrainingIdRouteWithChildren
  AuthenticatedTreinoDiagnosticoRoute: typeof AuthenticatedTreinoDiagnosticoRoute
  AuthenticatedTreinoEstudoRoute: typeof AuthenticatedTreinoEstudoRoute
  AuthenticatedTreinoFinalRoute: typeof AuthenticatedTreinoFinalRoute
  AuthenticatedTreinoNovoRoute: typeof AuthenticatedTreinoNovoRoute
  AuthenticatedTreinoProvaRoute: typeof AuthenticatedTreinoProvaRoute
  AuthenticatedTreinoRetentativaRoute: typeof AuthenticatedTreinoRetentativaRoute
  AuthenticatedTreinoIndexRoute: typeof AuthenticatedTreinoIndexRoute
}

const AuthenticatedTreinoRouteChildren: AuthenticatedTreinoRouteChildren = {
  AuthenticatedTreinoTrainingIdRoute:
    AuthenticatedTreinoTrainingIdRouteWithChildren,
  AuthenticatedTreinoDiagnosticoRoute: AuthenticatedTreinoDiagnosticoRoute,
  AuthenticatedTreinoEstudoRoute: AuthenticatedTreinoEstudoRoute,
  AuthenticatedTreinoFinalRoute: AuthenticatedTreinoFinalRoute,
  AuthenticatedTreinoNovoRoute: AuthenticatedTreinoNovoRoute,
  AuthenticatedTreinoProvaRoute: AuthenticatedTreinoProvaRoute,
  AuthenticatedTreinoRetentativaRoute: AuthenticatedTreinoRetentativaRoute,
  AuthenticatedTreinoIndexRoute: AuthenticatedTreinoIndexRoute,
}

const AuthenticatedTreinoRouteWithChildren =
  AuthenticatedTreinoRoute._addFileChildren(AuthenticatedTreinoRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedEvolucaoComoFuncionaRoute: typeof AuthenticatedEvolucaoComoFuncionaRoute
  AuthenticatedExamBasesRoute: typeof AuthenticatedExamBasesRoute
  AuthenticatedExamBoardsRoute: typeof AuthenticatedExamBoardsRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedTreinoRoute: typeof AuthenticatedTreinoRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedEvolucaoComoFuncionaRoute:
    AuthenticatedEvolucaoComoFuncionaRoute,
  AuthenticatedExamBasesRoute: AuthenticatedExamBasesRoute,
  AuthenticatedExamBoardsRoute: AuthenticatedExamBoardsRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedTreinoRoute: AuthenticatedTreinoRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
