/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExamBoardsRouteImport } from './routes/_authenticated/exam-boards'
import { Route as AuthenticatedExamBasesRouteImport } from './routes/_authenticated/exam-bases'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedExamsExamBoardIndexRouteImport } from './routes/_authenticated/exams/$examBoard/index'
import { Route as AuthenticatedExamsExamBoardExamIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/index'
import { Route as AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/$attemptId/index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamBoardsRoute = AuthenticatedExamBoardsRouteImport.update({
  id: '/exam-boards',
  path: '/exam-boards',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamBasesRoute = AuthenticatedExamBasesRouteImport.update({
  id: '/exam-bases',
  path: '/exam-bases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsExamBoardIndexRoute =
  AuthenticatedExamsExamBoardIndexRouteImport.update({
    id: '/exams/$examBoard/',
    path: '/exams/$examBoard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdIndexRouteImport.update({
    id: '/exams/$examBoard/$examId/',
    path: '/exams/$examBoard/$examId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport.update({
    id: '/exams/$examBoard/$examId/$attemptId/',
    path: '/exams/$examBoard/$examId/$attemptId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/exam-bases': typeof AuthenticatedExamBasesRoute
  '/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/exams/$examBoard/': typeof AuthenticatedExamsExamBoardIndexRoute
  '/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/exam-bases': typeof AuthenticatedExamBasesRoute
  '/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/exams/$examBoard': typeof AuthenticatedExamsExamBoardIndexRoute
  '/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/exams/$examBoard/$examId/$attemptId': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/exam-bases': typeof AuthenticatedExamBasesRoute
  '/_authenticated/exam-boards': typeof AuthenticatedExamBoardsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/exams/$examBoard/': typeof AuthenticatedExamsExamBoardIndexRoute
  '/_authenticated/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/_authenticated/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/database'
    | '/exam-bases'
    | '/exam-boards'
    | '/history'
    | '/exams/'
    | '/exams/$examBoard/'
    | '/exams/$examBoard/$examId/'
    | '/exams/$examBoard/$examId/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/database'
    | '/exam-bases'
    | '/exam-boards'
    | '/history'
    | '/exams'
    | '/exams/$examBoard'
    | '/exams/$examBoard/$examId'
    | '/exams/$examBoard/$examId/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/database'
    | '/_authenticated/exam-bases'
    | '/_authenticated/exam-boards'
    | '/_authenticated/history'
    | '/_authenticated/exams/'
    | '/_authenticated/exams/$examBoard/'
    | '/_authenticated/exams/$examBoard/$examId/'
    | '/_authenticated/exams/$examBoard/$examId/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-boards': {
      id: '/_authenticated/exam-boards'
      path: '/exam-boards'
      fullPath: '/exam-boards'
      preLoaderRoute: typeof AuthenticatedExamBoardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam-bases': {
      id: '/_authenticated/exam-bases'
      path: '/exam-bases'
      fullPath: '/exam-bases'
      preLoaderRoute: typeof AuthenticatedExamBasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examBoard/': {
      id: '/_authenticated/exams/$examBoard/'
      path: '/exams/$examBoard'
      fullPath: '/exams/$examBoard/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examBoard/$examId/': {
      id: '/_authenticated/exams/$examBoard/$examId/'
      path: '/exams/$examBoard/$examId'
      fullPath: '/exams/$examBoard/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examBoard/$examId/$attemptId/': {
      id: '/_authenticated/exams/$examBoard/$examId/$attemptId/'
      path: '/exams/$examBoard/$examId/$attemptId'
      fullPath: '/exams/$examBoard/$examId/$attemptId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedExamBasesRoute: typeof AuthenticatedExamBasesRoute
  AuthenticatedExamBoardsRoute: typeof AuthenticatedExamBoardsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedExamsExamBoardIndexRoute: typeof AuthenticatedExamsExamBoardIndexRoute
  AuthenticatedExamsExamBoardExamIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedExamBasesRoute: AuthenticatedExamBasesRoute,
  AuthenticatedExamBoardsRoute: AuthenticatedExamBoardsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedExamsExamBoardIndexRoute: AuthenticatedExamsExamBoardIndexRoute,
  AuthenticatedExamsExamBoardExamIdIndexRoute:
    AuthenticatedExamsExamBoardExamIdIndexRoute,
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute:
    AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
