/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MobilePreviewRouteImport } from './routes/mobile-preview'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlanosRouteImport } from './routes/_authenticated/planos'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedExamsRouteImport } from './routes/_authenticated/exams'
import { Route as AuthenticatedEvolucaoComoFuncionaRouteImport } from './routes/_authenticated/evolucao-como-funciona'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutSuccessRouteImport } from './routes/_authenticated/checkout-success'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedTreinoIndexRouteImport } from './routes/_authenticated/treino/index'
import { Route as AuthenticatedExamsIndexRouteImport } from './routes/_authenticated/exams/index'
import { Route as AuthenticatedConcursosIndexRouteImport } from './routes/_authenticated/concursos/index'
import { Route as AuthenticatedTreinoSplatRouteImport } from './routes/_authenticated/treino/$'
import { Route as AuthenticatedExamsEditarRouteImport } from './routes/_authenticated/exams/editar'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminPciScraperRouteImport } from './routes/_authenticated/admin/pci-scraper'
import { Route as AuthenticatedAdminDocumentScraperRouteImport } from './routes/_authenticated/admin/document-scraper'
import { Route as AuthenticatedAdminCriarConcursoRouteImport } from './routes/_authenticated/admin/criar-concurso'
import { Route as AuthenticatedConcursosConcursoSlugIndexRouteImport } from './routes/_authenticated/concursos/$concursoSlug/index'
import { Route as AuthenticatedExamsEditarExamBaseIdRouteImport } from './routes/_authenticated/exams/editar/$examBaseId'
import { Route as AuthenticatedExamsExamBoardExamIdRouteImport } from './routes/_authenticated/exams/$examBoard/$examId'
import { Route as AuthenticatedConcursosConcursoSlugCargoSlugRouteImport } from './routes/_authenticated/concursos/$concursoSlug/$cargoSlug'
import { Route as AuthenticatedAdminEditarConcursoConcursoIdRouteImport } from './routes/_authenticated/admin/editar-concurso.$concursoId'
import { Route as AuthenticatedExamsExamBoardExamIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/index'
import { Route as AuthenticatedExamsExamBoardExamIdQuestoesV2RouteImport } from './routes/_authenticated/exams/$examBoard/$examId/questoes-v2'
import { Route as AuthenticatedExamsExamBoardExamIdQuestoesRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/questoes'
import { Route as AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/$attemptId/index'
import { Route as AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport } from './routes/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilePreviewRoute = MobilePreviewRouteImport.update({
  id: '/mobile-preview',
  path: '/mobile-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanosRoute = AuthenticatedPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExamsRoute = AuthenticatedExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvolucaoComoFuncionaRoute =
  AuthenticatedEvolucaoComoFuncionaRouteImport.update({
    id: '/evolucao-como-funciona',
    path: '/evolucao-como-funciona',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCheckoutSuccessRoute =
  AuthenticatedCheckoutSuccessRouteImport.update({
    id: '/checkout-success',
    path: '/checkout-success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTreinoIndexRoute =
  AuthenticatedTreinoIndexRouteImport.update({
    id: '/treino/',
    path: '/treino/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsIndexRoute = AuthenticatedExamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedExamsRoute,
} as any)
const AuthenticatedConcursosIndexRoute =
  AuthenticatedConcursosIndexRouteImport.update({
    id: '/concursos/',
    path: '/concursos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreinoSplatRoute =
  AuthenticatedTreinoSplatRouteImport.update({
    id: '/treino/$',
    path: '/treino/$',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsEditarRoute =
  AuthenticatedExamsEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPciScraperRoute =
  AuthenticatedAdminPciScraperRouteImport.update({
    id: '/admin/pci-scraper',
    path: '/admin/pci-scraper',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentScraperRoute =
  AuthenticatedAdminDocumentScraperRouteImport.update({
    id: '/admin/document-scraper',
    path: '/admin/document-scraper',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCriarConcursoRoute =
  AuthenticatedAdminCriarConcursoRouteImport.update({
    id: '/admin/criar-concurso',
    path: '/admin/criar-concurso',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConcursosConcursoSlugIndexRoute =
  AuthenticatedConcursosConcursoSlugIndexRouteImport.update({
    id: '/concursos/$concursoSlug/',
    path: '/concursos/$concursoSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsEditarExamBaseIdRoute =
  AuthenticatedExamsEditarExamBaseIdRouteImport.update({
    id: '/$examBaseId',
    path: '/$examBaseId',
    getParentRoute: () => AuthenticatedExamsEditarRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdRoute =
  AuthenticatedExamsExamBoardExamIdRouteImport.update({
    id: '/$examBoard/$examId',
    path: '/$examBoard/$examId',
    getParentRoute: () => AuthenticatedExamsRoute,
  } as any)
const AuthenticatedConcursosConcursoSlugCargoSlugRoute =
  AuthenticatedConcursosConcursoSlugCargoSlugRouteImport.update({
    id: '/concursos/$concursoSlug/$cargoSlug',
    path: '/concursos/$concursoSlug/$cargoSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminEditarConcursoConcursoIdRoute =
  AuthenticatedAdminEditarConcursoConcursoIdRouteImport.update({
    id: '/admin/editar-concurso/$concursoId',
    path: '/admin/editar-concurso/$concursoId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdQuestoesV2Route =
  AuthenticatedExamsExamBoardExamIdQuestoesV2RouteImport.update({
    id: '/questoes-v2',
    path: '/questoes-v2',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdQuestoesRoute =
  AuthenticatedExamsExamBoardExamIdQuestoesRouteImport.update({
    id: '/questoes',
    path: '/questoes',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute =
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport.update({
    id: '/$attemptId/',
    path: '/$attemptId/',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)
const AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute =
  AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport.update({
    id: '/$attemptId/feedback',
    path: '/$attemptId/feedback',
    getParentRoute: () => AuthenticatedExamsExamBoardExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/exams': typeof AuthenticatedExamsRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/admin/criar-concurso': typeof AuthenticatedAdminCriarConcursoRoute
  '/admin/document-scraper': typeof AuthenticatedAdminDocumentScraperRoute
  '/admin/pci-scraper': typeof AuthenticatedAdminPciScraperRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/exams/editar': typeof AuthenticatedExamsEditarRouteWithChildren
  '/treino/$': typeof AuthenticatedTreinoSplatRoute
  '/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/exams/': typeof AuthenticatedExamsIndexRoute
  '/treino/': typeof AuthenticatedTreinoIndexRoute
  '/admin/editar-concurso/$concursoId': typeof AuthenticatedAdminEditarConcursoConcursoIdRoute
  '/concursos/$concursoSlug/$cargoSlug': typeof AuthenticatedConcursosConcursoSlugCargoSlugRoute
  '/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
  '/exams/editar/$examBaseId': typeof AuthenticatedExamsEditarExamBaseIdRoute
  '/concursos/$concursoSlug/': typeof AuthenticatedConcursosConcursoSlugIndexRoute
  '/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/exams/$examBoard/$examId/questoes-v2': typeof AuthenticatedExamsExamBoardExamIdQuestoesV2Route
  '/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mobile-preview': typeof MobilePreviewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/account': typeof AuthenticatedAccountRoute
  '/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/planos': typeof AuthenticatedPlanosRoute
  '/admin/criar-concurso': typeof AuthenticatedAdminCriarConcursoRoute
  '/admin/document-scraper': typeof AuthenticatedAdminDocumentScraperRoute
  '/admin/pci-scraper': typeof AuthenticatedAdminPciScraperRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/exams/editar': typeof AuthenticatedExamsEditarRouteWithChildren
  '/treino/$': typeof AuthenticatedTreinoSplatRoute
  '/concursos': typeof AuthenticatedConcursosIndexRoute
  '/exams': typeof AuthenticatedExamsIndexRoute
  '/treino': typeof AuthenticatedTreinoIndexRoute
  '/admin/editar-concurso/$concursoId': typeof AuthenticatedAdminEditarConcursoConcursoIdRoute
  '/concursos/$concursoSlug/$cargoSlug': typeof AuthenticatedConcursosConcursoSlugCargoSlugRoute
  '/exams/editar/$examBaseId': typeof AuthenticatedExamsEditarExamBaseIdRoute
  '/concursos/$concursoSlug': typeof AuthenticatedConcursosConcursoSlugIndexRoute
  '/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/exams/$examBoard/$examId/questoes-v2': typeof AuthenticatedExamsExamBoardExamIdQuestoesV2Route
  '/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/exams/$examBoard/$examId/$attemptId': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/mobile-preview': typeof MobilePreviewRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/checkout-success': typeof AuthenticatedCheckoutSuccessRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/evolucao-como-funciona': typeof AuthenticatedEvolucaoComoFuncionaRoute
  '/_authenticated/exams': typeof AuthenticatedExamsRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/planos': typeof AuthenticatedPlanosRoute
  '/_authenticated/admin/criar-concurso': typeof AuthenticatedAdminCriarConcursoRoute
  '/_authenticated/admin/document-scraper': typeof AuthenticatedAdminDocumentScraperRoute
  '/_authenticated/admin/pci-scraper': typeof AuthenticatedAdminPciScraperRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/exams/editar': typeof AuthenticatedExamsEditarRouteWithChildren
  '/_authenticated/treino/$': typeof AuthenticatedTreinoSplatRoute
  '/_authenticated/concursos/': typeof AuthenticatedConcursosIndexRoute
  '/_authenticated/exams/': typeof AuthenticatedExamsIndexRoute
  '/_authenticated/treino/': typeof AuthenticatedTreinoIndexRoute
  '/_authenticated/admin/editar-concurso/$concursoId': typeof AuthenticatedAdminEditarConcursoConcursoIdRoute
  '/_authenticated/concursos/$concursoSlug/$cargoSlug': typeof AuthenticatedConcursosConcursoSlugCargoSlugRoute
  '/_authenticated/exams/$examBoard/$examId': typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
  '/_authenticated/exams/editar/$examBaseId': typeof AuthenticatedExamsEditarExamBaseIdRoute
  '/_authenticated/concursos/$concursoSlug/': typeof AuthenticatedConcursosConcursoSlugIndexRoute
  '/_authenticated/exams/$examBoard/$examId/questoes': typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  '/_authenticated/exams/$examBoard/$examId/questoes-v2': typeof AuthenticatedExamsExamBoardExamIdQuestoesV2Route
  '/_authenticated/exams/$examBoard/$examId/': typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback': typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  '/_authenticated/exams/$examBoard/$examId/$attemptId/': typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mobile-preview'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/checkout-success'
    | '/dashboard'
    | '/evolucao-como-funciona'
    | '/exams'
    | '/onboarding'
    | '/planos'
    | '/admin/criar-concurso'
    | '/admin/document-scraper'
    | '/admin/pci-scraper'
    | '/admin/users'
    | '/exams/editar'
    | '/treino/$'
    | '/concursos/'
    | '/exams/'
    | '/treino/'
    | '/admin/editar-concurso/$concursoId'
    | '/concursos/$concursoSlug/$cargoSlug'
    | '/exams/$examBoard/$examId'
    | '/exams/editar/$examBaseId'
    | '/concursos/$concursoSlug/'
    | '/exams/$examBoard/$examId/questoes'
    | '/exams/$examBoard/$examId/questoes-v2'
    | '/exams/$examBoard/$examId/'
    | '/exams/$examBoard/$examId/$attemptId/feedback'
    | '/exams/$examBoard/$examId/$attemptId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mobile-preview'
    | '/sign-in'
    | '/sign-up'
    | '/account'
    | '/checkout-success'
    | '/dashboard'
    | '/evolucao-como-funciona'
    | '/onboarding'
    | '/planos'
    | '/admin/criar-concurso'
    | '/admin/document-scraper'
    | '/admin/pci-scraper'
    | '/admin/users'
    | '/exams/editar'
    | '/treino/$'
    | '/concursos'
    | '/exams'
    | '/treino'
    | '/admin/editar-concurso/$concursoId'
    | '/concursos/$concursoSlug/$cargoSlug'
    | '/exams/editar/$examBaseId'
    | '/concursos/$concursoSlug'
    | '/exams/$examBoard/$examId/questoes'
    | '/exams/$examBoard/$examId/questoes-v2'
    | '/exams/$examBoard/$examId'
    | '/exams/$examBoard/$examId/$attemptId/feedback'
    | '/exams/$examBoard/$examId/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/mobile-preview'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/account'
    | '/_authenticated/checkout-success'
    | '/_authenticated/dashboard'
    | '/_authenticated/evolucao-como-funciona'
    | '/_authenticated/exams'
    | '/_authenticated/onboarding'
    | '/_authenticated/planos'
    | '/_authenticated/admin/criar-concurso'
    | '/_authenticated/admin/document-scraper'
    | '/_authenticated/admin/pci-scraper'
    | '/_authenticated/admin/users'
    | '/_authenticated/exams/editar'
    | '/_authenticated/treino/$'
    | '/_authenticated/concursos/'
    | '/_authenticated/exams/'
    | '/_authenticated/treino/'
    | '/_authenticated/admin/editar-concurso/$concursoId'
    | '/_authenticated/concursos/$concursoSlug/$cargoSlug'
    | '/_authenticated/exams/$examBoard/$examId'
    | '/_authenticated/exams/editar/$examBaseId'
    | '/_authenticated/concursos/$concursoSlug/'
    | '/_authenticated/exams/$examBoard/$examId/questoes'
    | '/_authenticated/exams/$examBoard/$examId/questoes-v2'
    | '/_authenticated/exams/$examBoard/$examId/'
    | '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'
    | '/_authenticated/exams/$examBoard/$examId/$attemptId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  MobilePreviewRoute: typeof MobilePreviewRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-preview': {
      id: '/mobile-preview'
      path: '/mobile-preview'
      fullPath: '/mobile-preview'
      preLoaderRoute: typeof MobilePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/planos': {
      id: '/_authenticated/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AuthenticatedPlanosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams': {
      id: '/_authenticated/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AuthenticatedExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evolucao-como-funciona': {
      id: '/_authenticated/evolucao-como-funciona'
      path: '/evolucao-como-funciona'
      fullPath: '/evolucao-como-funciona'
      preLoaderRoute: typeof AuthenticatedEvolucaoComoFuncionaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout-success': {
      id: '/_authenticated/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof AuthenticatedCheckoutSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treino/': {
      id: '/_authenticated/treino/'
      path: '/treino'
      fullPath: '/treino/'
      preLoaderRoute: typeof AuthenticatedTreinoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/': {
      id: '/_authenticated/exams/'
      path: '/'
      fullPath: '/exams/'
      preLoaderRoute: typeof AuthenticatedExamsIndexRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/concursos/': {
      id: '/_authenticated/concursos/'
      path: '/concursos'
      fullPath: '/concursos/'
      preLoaderRoute: typeof AuthenticatedConcursosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treino/$': {
      id: '/_authenticated/treino/$'
      path: '/treino/$'
      fullPath: '/treino/$'
      preLoaderRoute: typeof AuthenticatedTreinoSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/editar': {
      id: '/_authenticated/exams/editar'
      path: '/editar'
      fullPath: '/exams/editar'
      preLoaderRoute: typeof AuthenticatedExamsEditarRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pci-scraper': {
      id: '/_authenticated/admin/pci-scraper'
      path: '/admin/pci-scraper'
      fullPath: '/admin/pci-scraper'
      preLoaderRoute: typeof AuthenticatedAdminPciScraperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/document-scraper': {
      id: '/_authenticated/admin/document-scraper'
      path: '/admin/document-scraper'
      fullPath: '/admin/document-scraper'
      preLoaderRoute: typeof AuthenticatedAdminDocumentScraperRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/criar-concurso': {
      id: '/_authenticated/admin/criar-concurso'
      path: '/admin/criar-concurso'
      fullPath: '/admin/criar-concurso'
      preLoaderRoute: typeof AuthenticatedAdminCriarConcursoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concursos/$concursoSlug/': {
      id: '/_authenticated/concursos/$concursoSlug/'
      path: '/concursos/$concursoSlug'
      fullPath: '/concursos/$concursoSlug/'
      preLoaderRoute: typeof AuthenticatedConcursosConcursoSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/editar/$examBaseId': {
      id: '/_authenticated/exams/editar/$examBaseId'
      path: '/$examBaseId'
      fullPath: '/exams/editar/$examBaseId'
      preLoaderRoute: typeof AuthenticatedExamsEditarExamBaseIdRouteImport
      parentRoute: typeof AuthenticatedExamsEditarRoute
    }
    '/_authenticated/exams/$examBoard/$examId': {
      id: '/_authenticated/exams/$examBoard/$examId'
      path: '/$examBoard/$examId'
      fullPath: '/exams/$examBoard/$examId'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdRouteImport
      parentRoute: typeof AuthenticatedExamsRoute
    }
    '/_authenticated/concursos/$concursoSlug/$cargoSlug': {
      id: '/_authenticated/concursos/$concursoSlug/$cargoSlug'
      path: '/concursos/$concursoSlug/$cargoSlug'
      fullPath: '/concursos/$concursoSlug/$cargoSlug'
      preLoaderRoute: typeof AuthenticatedConcursosConcursoSlugCargoSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/editar-concurso/$concursoId': {
      id: '/_authenticated/admin/editar-concurso/$concursoId'
      path: '/admin/editar-concurso/$concursoId'
      fullPath: '/admin/editar-concurso/$concursoId'
      preLoaderRoute: typeof AuthenticatedAdminEditarConcursoConcursoIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exams/$examBoard/$examId/': {
      id: '/_authenticated/exams/$examBoard/$examId/'
      path: '/'
      fullPath: '/exams/$examBoard/$examId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/questoes-v2': {
      id: '/_authenticated/exams/$examBoard/$examId/questoes-v2'
      path: '/questoes-v2'
      fullPath: '/exams/$examBoard/$examId/questoes-v2'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdQuestoesV2RouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/questoes': {
      id: '/_authenticated/exams/$examBoard/$examId/questoes'
      path: '/questoes'
      fullPath: '/exams/$examBoard/$examId/questoes'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdQuestoesRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/$attemptId/': {
      id: '/_authenticated/exams/$examBoard/$examId/$attemptId/'
      path: '/$attemptId'
      fullPath: '/exams/$examBoard/$examId/$attemptId/'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
    '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback': {
      id: '/_authenticated/exams/$examBoard/$examId/$attemptId/feedback'
      path: '/$attemptId/feedback'
      fullPath: '/exams/$examBoard/$examId/$attemptId/feedback'
      preLoaderRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedExamsExamBoardExamIdRoute
    }
  }
}

interface AuthenticatedExamsEditarRouteChildren {
  AuthenticatedExamsEditarExamBaseIdRoute: typeof AuthenticatedExamsEditarExamBaseIdRoute
}

const AuthenticatedExamsEditarRouteChildren: AuthenticatedExamsEditarRouteChildren =
  {
    AuthenticatedExamsEditarExamBaseIdRoute:
      AuthenticatedExamsEditarExamBaseIdRoute,
  }

const AuthenticatedExamsEditarRouteWithChildren =
  AuthenticatedExamsEditarRoute._addFileChildren(
    AuthenticatedExamsEditarRouteChildren,
  )

interface AuthenticatedExamsExamBoardExamIdRouteChildren {
  AuthenticatedExamsExamBoardExamIdQuestoesRoute: typeof AuthenticatedExamsExamBoardExamIdQuestoesRoute
  AuthenticatedExamsExamBoardExamIdQuestoesV2Route: typeof AuthenticatedExamsExamBoardExamIdQuestoesV2Route
  AuthenticatedExamsExamBoardExamIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdIndexRoute
  AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute
  AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute: typeof AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute
}

const AuthenticatedExamsExamBoardExamIdRouteChildren: AuthenticatedExamsExamBoardExamIdRouteChildren =
  {
    AuthenticatedExamsExamBoardExamIdQuestoesRoute:
      AuthenticatedExamsExamBoardExamIdQuestoesRoute,
    AuthenticatedExamsExamBoardExamIdQuestoesV2Route:
      AuthenticatedExamsExamBoardExamIdQuestoesV2Route,
    AuthenticatedExamsExamBoardExamIdIndexRoute:
      AuthenticatedExamsExamBoardExamIdIndexRoute,
    AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute:
      AuthenticatedExamsExamBoardExamIdAttemptIdFeedbackRoute,
    AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute:
      AuthenticatedExamsExamBoardExamIdAttemptIdIndexRoute,
  }

const AuthenticatedExamsExamBoardExamIdRouteWithChildren =
  AuthenticatedExamsExamBoardExamIdRoute._addFileChildren(
    AuthenticatedExamsExamBoardExamIdRouteChildren,
  )

interface AuthenticatedExamsRouteChildren {
  AuthenticatedExamsEditarRoute: typeof AuthenticatedExamsEditarRouteWithChildren
  AuthenticatedExamsIndexRoute: typeof AuthenticatedExamsIndexRoute
  AuthenticatedExamsExamBoardExamIdRoute: typeof AuthenticatedExamsExamBoardExamIdRouteWithChildren
}

const AuthenticatedExamsRouteChildren: AuthenticatedExamsRouteChildren = {
  AuthenticatedExamsEditarRoute: AuthenticatedExamsEditarRouteWithChildren,
  AuthenticatedExamsIndexRoute: AuthenticatedExamsIndexRoute,
  AuthenticatedExamsExamBoardExamIdRoute:
    AuthenticatedExamsExamBoardExamIdRouteWithChildren,
}

const AuthenticatedExamsRouteWithChildren =
  AuthenticatedExamsRoute._addFileChildren(AuthenticatedExamsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedCheckoutSuccessRoute: typeof AuthenticatedCheckoutSuccessRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEvolucaoComoFuncionaRoute: typeof AuthenticatedEvolucaoComoFuncionaRoute
  AuthenticatedExamsRoute: typeof AuthenticatedExamsRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlanosRoute: typeof AuthenticatedPlanosRoute
  AuthenticatedAdminCriarConcursoRoute: typeof AuthenticatedAdminCriarConcursoRoute
  AuthenticatedAdminDocumentScraperRoute: typeof AuthenticatedAdminDocumentScraperRoute
  AuthenticatedAdminPciScraperRoute: typeof AuthenticatedAdminPciScraperRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedTreinoSplatRoute: typeof AuthenticatedTreinoSplatRoute
  AuthenticatedConcursosIndexRoute: typeof AuthenticatedConcursosIndexRoute
  AuthenticatedTreinoIndexRoute: typeof AuthenticatedTreinoIndexRoute
  AuthenticatedAdminEditarConcursoConcursoIdRoute: typeof AuthenticatedAdminEditarConcursoConcursoIdRoute
  AuthenticatedConcursosConcursoSlugCargoSlugRoute: typeof AuthenticatedConcursosConcursoSlugCargoSlugRoute
  AuthenticatedConcursosConcursoSlugIndexRoute: typeof AuthenticatedConcursosConcursoSlugIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedCheckoutSuccessRoute: AuthenticatedCheckoutSuccessRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEvolucaoComoFuncionaRoute:
    AuthenticatedEvolucaoComoFuncionaRoute,
  AuthenticatedExamsRoute: AuthenticatedExamsRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlanosRoute: AuthenticatedPlanosRoute,
  AuthenticatedAdminCriarConcursoRoute: AuthenticatedAdminCriarConcursoRoute,
  AuthenticatedAdminDocumentScraperRoute:
    AuthenticatedAdminDocumentScraperRoute,
  AuthenticatedAdminPciScraperRoute: AuthenticatedAdminPciScraperRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedTreinoSplatRoute: AuthenticatedTreinoSplatRoute,
  AuthenticatedConcursosIndexRoute: AuthenticatedConcursosIndexRoute,
  AuthenticatedTreinoIndexRoute: AuthenticatedTreinoIndexRoute,
  AuthenticatedAdminEditarConcursoConcursoIdRoute:
    AuthenticatedAdminEditarConcursoConcursoIdRoute,
  AuthenticatedConcursosConcursoSlugCargoSlugRoute:
    AuthenticatedConcursosConcursoSlugCargoSlugRoute,
  AuthenticatedConcursosConcursoSlugIndexRoute:
    AuthenticatedConcursosConcursoSlugIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  MobilePreviewRoute: MobilePreviewRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
